# Generated by Django 3.1.5 on 2021-01-29 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210130_0238'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SomeModel',
        ),
    ]
